//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintBucket.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintBucket.Web.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I accept the terms and conditions.
        /// </summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access your space.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access.
        /// </summary>
        public static string AccessButton {
            get {
                return ResourceManager.GetString("AccessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while validating the access code. Please try again later..
        /// </summary>
        public static string AccessCode_Error {
            get {
                return ResourceManager.GetString("AccessCode_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid access code. Please check and try again..
        /// </summary>
        public static string AccessCode_Invalid {
            get {
                return ResourceManager.GetString("AccessCode_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access code must be between {2} and {1} characters.
        /// </summary>
        public static string AccessCode_Length {
            get {
                return ResourceManager.GetString("AccessCode_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access code is required.
        /// </summary>
        public static string AccessCode_Required {
            get {
                return ResourceManager.GetString("AccessCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access Code.
        /// </summary>
        public static string AccessCodeLabel {
            get {
                return ResourceManager.GetString("AccessCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use access code.
        /// </summary>
        public static string AccessCodeTitle {
            get {
                return ResourceManager.GetString("AccessCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use your device&apos;s camera to scan your space&apos;s QR code.
        /// </summary>
        public static string AccessQRDescription {
            get {
                return ResourceManager.GetString("AccessQRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan QR code.
        /// </summary>
        public static string AccessQRTitle {
            get {
                return ResourceManager.GetString("AccessQRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access your space.
        /// </summary>
        public static string AccessTitle {
            get {
                return ResourceManager.GetString("AccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add photos.
        /// </summary>
        public static string AddPhotos {
            get {
                return ResourceManager.GetString("AddPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analyze image with AI.
        /// </summary>
        public static string AnalyzeImage {
            get {
                return ResourceManager.GetString("AnalyzeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Space details.
        /// </summary>
        public static string BucketViewTitle {
            get {
                return ResourceManager.GetString("BucketViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while creating your bucket. Please try again later..
        /// </summary>
        public static string CreateBucket_Error {
            get {
                return ResourceManager.GetString("CreateBucket_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create space.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create your personalized space.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We&apos;ll send you an access code to this email.
        /// </summary>
        public static string EmailHelp {
            get {
                return ResourceManager.GetString("EmailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email address.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private · Secure · Easy to share.
        /// </summary>
        public static string HeroBenefits {
            get {
                return ResourceManager.GetString("HeroBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Say goodbye to losing photos in endless chats..
        /// </summary>
        public static string HeroHeadline {
            get {
                return ResourceManager.GetString("HeroHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your wedding, trip, or birthday—all your memories in one shared album. Organize them effortlessly, personalize them with AI... and transform them into beautiful prints whenever you wish..
        /// </summary>
        public static string HeroSubhead {
            get {
                return ResourceManager.GetString("HeroSubhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home page.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PrintBucket hero image.
        /// </summary>
        public static string ImageAlt {
            get {
                return ResourceManager.GetString("ImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access your space.
        /// </summary>
        public static string NavAccess {
            get {
                return ResourceManager.GetString("NavAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create your space.
        /// </summary>
        public static string NavCreate {
            get {
                return ResourceManager.GetString("NavCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order high-quality prints.
        /// </summary>
        public static string PrintsNote {
            get {
                return ResourceManager.GetString("PrintsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We may update this policy. We will post changes here with a revised effective date..
        /// </summary>
        public static string Privacy_Changes {
            get {
                return ResourceManager.GetString("Privacy_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Changes to this policy.
        /// </summary>
        public static string Privacy_ChangesTitle {
            get {
                return ResourceManager.GetString("Privacy_ChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The service is not intended for children under 13. We do not knowingly collect personal data from children..
        /// </summary>
        public static string Privacy_Children {
            get {
                return ResourceManager.GetString("Privacy_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Children.
        /// </summary>
        public static string Privacy_ChildrenTitle {
            get {
                return ResourceManager.GetString("Privacy_ChildrenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For privacy questions contact: dario@parresibarra.com.
        /// </summary>
        public static string Privacy_Contact {
            get {
                return ResourceManager.GetString("Privacy_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        public static string Privacy_ContactTitle {
            get {
                return ResourceManager.GetString("Privacy_ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optional diagnostic and error reports (stack traces, logs) if you enable them to help us improve the product..
        /// </summary>
        public static string Privacy_DataCollected_Diagnostics {
            get {
                return ResourceManager.GetString("Privacy_DataCollected_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files you upload (images), associated metadata (file names, bucket IDs) and optional descriptions you provide..
        /// </summary>
        public static string Privacy_DataCollected_FileUploads {
            get {
                return ResourceManager.GetString("Privacy_DataCollected_FileUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usage data such as IP address, timestamps, request logs and performance metrics necessary to operate the service..
        /// </summary>
        public static string Privacy_DataCollected_Usage {
            get {
                return ResourceManager.GetString("Privacy_DataCollected_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data we collect.
        /// </summary>
        public static string Privacy_DataCollectedTitle {
            get {
                return ResourceManager.GetString("Privacy_DataCollectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We use data to provide, operate and improve the service, to process uploads, to respond to support requests and to detect abuse..
        /// </summary>
        public static string Privacy_HowWeUse {
            get {
                return ResourceManager.GetString("Privacy_HowWeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How we use your data.
        /// </summary>
        public static string Privacy_HowWeUseTitle {
            get {
                return ResourceManager.GetString("Privacy_HowWeUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;This privacy policy explains how PrintBucket collects, uses and discloses information when you use the Web UI and API.&lt;/p&gt;.
        /// </summary>
        public static string Privacy_Intro {
            get {
                return ResourceManager.GetString("Privacy_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uploaded files and metadata are retained while your bucket exists or as required by law. You can request deletion; removal may take time to propagate..
        /// </summary>
        public static string Privacy_Retention {
            get {
                return ResourceManager.GetString("Privacy_Retention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data retention.
        /// </summary>
        public static string Privacy_RetentionTitle {
            get {
                return ResourceManager.GetString("Privacy_RetentionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We apply standard security measures (TLS in transit, AWS access controls). The protection of stored objects depends on bucket policies and correct configuration..
        /// </summary>
        public static string Privacy_Security {
            get {
                return ResourceManager.GetString("Privacy_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Security.
        /// </summary>
        public static string Privacy_SecurityTitle {
            get {
                return ResourceManager.GetString("Privacy_SecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We use AWS services (S3, DynamoDB) and may use external analytics or monitoring providers. Their privacy policies apply to data they process..
        /// </summary>
        public static string Privacy_ThirdParties {
            get {
                return ResourceManager.GetString("Privacy_ThirdParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Third‑party services.
        /// </summary>
        public static string Privacy_ThirdPartiesTitle_ {
            get {
                return ResourceManager.GetString("Privacy_ThirdPartiesTitle ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy Policy.
        /// </summary>
        public static string Privacy_Title {
            get {
                return ResourceManager.GetString("Privacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You may request access, correction or deletion of personal data. Contact support and provide identification to exercise these rights..
        /// </summary>
        public static string Privacy_YourRights {
            get {
                return ResourceManager.GetString("Privacy_YourRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your rights.
        /// </summary>
        public static string Privacy_YourRightsTitle {
            get {
                return ResourceManager.GetString("Privacy_YourRightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share instantly via QR code.
        /// </summary>
        public static string QRCodeNote {
            get {
                return ResourceManager.GetString("QRCodeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not access camera.
        /// </summary>
        public static string QRScan_Error {
            get {
                return ResourceManager.GetString("QRScan_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Point the camera at a QR code.
        /// </summary>
        public static string QRScan_Instructions {
            get {
                return ResourceManager.GetString("QRScan_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requesting camera access....
        /// </summary>
        public static string QRScan_Requesting {
            get {
                return ResourceManager.GetString("QRScan_Requesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searching for QR code....
        /// </summary>
        public static string QRScan_Searching {
            get {
                return ResourceManager.GetString("QRScan_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan QR.
        /// </summary>
        public static string ScanQRButton {
            get {
                return ResourceManager.GetString("ScanQRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan QR Code.
        /// </summary>
        public static string ScanQRTitle {
            get {
                return ResourceManager.GetString("ScanQRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create my space.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
